
name: Java CI with Maven

'on':
  push:
    branches:
     - master
     - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
    
  build-image:
    name: Build Docker image
    needs: [ build ]
    steps:
      - name: Build & Push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v3
        with: 
          image: aradevic/pergamino-images:v1
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}