
name: Java CI with Maven

'on':
  push:
    branches:
     - master
     - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven
      
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          BUILD_NUMBER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $BUILD_NUMBER >> $GITHUB_ENV
    
      - name: Build Image
        run: |
          docker build -t aradevic/pergamino-images:$BUILD_NUMBER .
      
      - name: Push Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push aradevic/pergamino-images:$BUILD_NUMBER
        
        # uses: mr-smithers-excellent/docker-build-push@v3
        # with: 
        #   image: aradevic/pergamino-images
        #   registry: docker.io
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}